services:

  nginx:
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/cert.pem:/etc/nginx/cert.pem
      - ./nginx/key.pem:/etc/nginx/key.pem
      - static_volume:/usr/share/nginx/html/staticfiles
    depends_on:
      - django

  django:
    build: 
      context: ./project
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/project/staticfiles
    env_file:
      - ./project/.env
    expose:
      - "8000"

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - django
    expose:
      - "3000"

  
volumes:
  static_volume: