# Generated by Django 4.2.16 on 2025-04-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="название документа",
                        max_length=64,
                        verbose_name="название",
                    ),
                ),
            ],
            options={
                "verbose_name": "тип документ",
                "verbose_name_plural": "типы документов",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        choices=[
                            ("IRS", "В сельском поселении"),
                            ("OTS", "за пределами поселения"),
                            ("OTA", "за пределами района"),
                        ],
                        help_text="место работы",
                        max_length=64,
                        verbose_name="место работы",
                    ),
                ),
                (
                    "sphere",
                    models.CharField(
                        choices=[
                            ("E", "Образование"),
                            ("SP", "социальная защита"),
                            ("H", "Здравоохранение"),
                            ("C", "Культура"),
                            ("T", "Торговля"),
                            ("IP", "ИП"),
                            ("O", "Прочее"),
                        ],
                        help_text="сфера работы",
                        max_length=64,
                        verbose_name="место работы",
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        help_text="профессия работы",
                        max_length=64,
                        verbose_name="профессия",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="дата приема на работу", verbose_name="дата"
                    ),
                ),
            ],
            options={
                "verbose_name": "работа",
                "verbose_name_plural": "работы",
            },
        ),
        migrations.CreateModel(
            name="Human",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="имя человека",
                        max_length=64,
                        verbose_name="имя",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="фамилия человека",
                        max_length=64,
                        verbose_name="фамилия",
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        help_text="отчество человека",
                        max_length=64,
                        null=True,
                        verbose_name="отчество",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Мужщина"), ("W", "Женщина")],
                        default=None,
                        help_text="пол человека",
                        max_length=1,
                        verbose_name="пол",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[("S", "Холост/Не замужем"), ("M", "В браке")],
                        help_text="семейное положение человека",
                        max_length=1,
                        verbose_name="семейное положение",
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("P", "дошкольное"),
                            ("H", "начальное общее"),
                            ("IG", "основное общее"),
                            ("BG", "среднее общее"),
                            ("AO", "среднее профессиональное"),
                            ("SV", "высшее"),
                        ],
                        help_text="образование человека",
                        max_length=2,
                        verbose_name="образование",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        help_text="день рождения человека",
                        verbose_name="день рождения",
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        blank=True,
                        help_text="работа человека",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="people.job",
                        verbose_name="работа",
                    ),
                ),
            ],
            options={
                "verbose_name": "человек",
                "verbose_name_plural": "люди",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        help_text="серия документа",
                        max_length=64,
                        verbose_name="серия",
                    ),
                ),
                (
                    "nomer",
                    models.PositiveIntegerField(
                        help_text="номер документа", verbose_name="номер"
                    ),
                ),
                (
                    "issued",
                    models.CharField(
                        help_text="кем выдан документ",
                        max_length=256,
                        verbose_name="кем выдан",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="дата выдачи документа",
                        verbose_name="дата выдачи",
                    ),
                ),
                (
                    "human",
                    models.OneToOneField(
                        help_text="человек документа",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.human",
                        verbose_name="человек",
                    ),
                ),
                (
                    "type_document",
                    models.ForeignKey(
                        help_text="тип документа",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.documenttype",
                        verbose_name="тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "документ",
                "verbose_name_plural": "документы",
            },
        ),
    ]
