# Generated by Django 4.2.16 on 2025-04-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_invalidity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invalidity",
            name="has_invalidity",
        ),
    ]
