# Generated by Django 4.2.16 on 2025-04-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_remove_invalidity_has_invalidity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invalidity",
            options={
                "verbose_name": "инвалидность",
                "verbose_name_plural": "инвалидности",
            },
        ),
        migrations.RemoveField(
            model_name="document",
            name="human",
        ),
        migrations.AddField(
            model_name="human",
            name="document",
            field=models.OneToOneField(
                default=1,
                help_text="документ человека",
                on_delete=django.db.models.deletion.PROTECT,
                to="people.document",
                verbose_name="человек",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="human",
            name="job",
            field=models.OneToOneField(
                blank=True,
                help_text="работа человека",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="people.job",
                verbose_name="работа",
            ),
        ),
        migrations.AlterField(
            model_name="invalidity",
            name="other_details",
            field=models.CharField(
                blank=True,
                help_text="прочие инвалидности",
                max_length=255,
                null=True,
                verbose_name="другое",
            ),
        ),
        migrations.CreateModel(
            name="Military",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("warrant", "Прапорщик (мичман)"),
                            ("sergeant", "Сержант (старшина)"),
                            ("soldier", "Солдат (матрос)"),
                        ],
                        help_text="воинский состав",
                        max_length=20,
                        verbose_name="состав",
                    ),
                ),
                (
                    "soldier_rank",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2"), ("3", "3")],
                        help_text="военнское звание",
                        max_length=20,
                        verbose_name="звание",
                    ),
                ),
                (
                    "military_district",
                    models.CharField(
                        choices=[("army", "РА"), ("navy", "ВМФ")],
                        help_text="группа военского учета",
                        max_length=10,
                        verbose_name="группа учёта",
                    ),
                ),
                (
                    "military_account_type",
                    models.CharField(
                        choices=[
                            ("general", "Общий"),
                            ("special", "Специальный"),
                        ],
                        help_text="группа военского учета",
                        max_length=10,
                        verbose_name="группа учета",
                    ),
                ),
                (
                    "human",
                    models.OneToOneField(
                        help_text="человек военнообязаности",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.human",
                        verbose_name="человек",
                    ),
                ),
            ],
            options={
                "verbose_name": "военнообязаность",
                "verbose_name_plural": "военнообязаности",
            },
        ),
    ]
