# Generated by Django 4.2.16 on 2025-04-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "people",
            "0004_alter_invalidity_options_remove_document_human_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttype",
            name="name",
            field=models.CharField(
                help_text="название документа",
                max_length=64,
                unique=True,
                verbose_name="название",
            ),
        ),
    ]
