# Generated by Django 4.2.16 on 2025-04-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0007_alter_military_soldier_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="military",
            name="military_account_type",
            field=models.CharField(
                choices=[("general", "Общий"), ("special", "Специальный")],
                help_text="вид военского учета",
                max_length=10,
                verbose_name="вид учета",
            ),
        ),
    ]
