# Generated by Django 4.2.16 on 2025-04-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0008_alter_military_military_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="military",
            name="military_category",
            field=models.PositiveIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3")],
                default=1,
                help_text="воинский разряд",
                max_length=1,
                verbose_name="разряд",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="military",
            name="stock_category",
            field=models.PositiveIntegerField(
                choices=[(1, "1"), (2, "2")],
                default=1,
                help_text="категория военского запаса",
                max_length=1,
                verbose_name="категория запаса",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invalidity",
            name="group",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "1 группа"), (2, "2 группа"), (3, "3 группа")],
                help_text="группа инвалидности",
                null=True,
                verbose_name="группа",
            ),
        ),
        migrations.AlterField(
            model_name="military",
            name="military_account_type",
            field=models.CharField(
                choices=[("general", "Общий"), ("special", "Специальный")],
                help_text="вид военского учета",
                max_length=7,
                verbose_name="вид учета",
            ),
        ),
        migrations.AlterField(
            model_name="military",
            name="military_district",
            field=models.CharField(
                choices=[("army", "РА"), ("navy", "ВМФ")],
                help_text="группа военского учета",
                max_length=4,
                verbose_name="группа учёта",
            ),
        ),
        migrations.AlterField(
            model_name="military",
            name="rank",
            field=models.CharField(
                choices=[
                    ("warrant", "Прапорщик (мичман)"),
                    ("sergeant", "Сержант (старшина)"),
                    ("soldier", "Солдат (матрос)"),
                ],
                help_text="воинский состав",
                max_length=8,
                verbose_name="состав",
            ),
        ),
        migrations.AlterField(
            model_name="military",
            name="soldier_rank",
            field=models.CharField(
                choices=[
                    ("private", "Рядовой"),
                    ("corporal", "Ефрейтор"),
                    ("junior_sergeant", "Младший сержант"),
                    ("sergeant", "Сержант"),
                    ("senior_sergeant", "Старший сержант"),
                    ("chief", "Старшина"),
                    ("warrant_officer", "Прапорщик"),
                    ("senior_warrant_officer", "Старший прапорщик"),
                ],
                help_text="военнское звание",
                max_length=22,
                verbose_name="звание",
            ),
        ),
    ]
