# Generated by Django 4.2.16 on 2025-04-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0010_alter_military_military_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="human",
            name="other_reason",
            field=models.CharField(
                blank=True,
                help_text="Укажите причину, если выбрано 'Другое'",
                max_length=255,
                null=True,
                verbose_name="другая причина",
            ),
        ),
        migrations.AddField(
            model_name="human",
            name="unemployment_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Студент"),
                    ("maternity_leave", "В декретном отпуске"),
                    ("care_for_sick", "По уходу за больным"),
                    ("disability", "Инвалиды по заболеванию"),
                    ("employed", "Трудоустраиваются"),
                    ("army", "В рядах РА"),
                    ("imprisoned", "В местах заключения"),
                    ("seasonal_work", "На сезонных работах"),
                    (
                        "unemployed",
                        "Безработные, стоящие на учёте в центре занятости",
                    ),
                    ("long_term_unemployed", "Неработающие более 3 лет"),
                    ("other", "Другое"),
                ],
                help_text="Причина отсутствия работы, если человек не работает",
                max_length=30,
                null=True,
                verbose_name="причина отсутствия работы",
            ),
        ),
    ]
