# Generated by Django 4.2.16 on 2025-04-03 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0011_human_other_reason_human_unemployment_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="адрес"),
                ),
                (
                    "registered_from",
                    models.DateField(
                        help_text="Дата начала регистрации",
                        verbose_name="зарегистрирован с",
                    ),
                ),
                (
                    "registered_to",
                    models.DateField(
                        help_text="Дата окончания регистрации",
                        verbose_name="зарегистрирован по",
                    ),
                ),
            ],
            options={
                "verbose_name": "регистрация",
                "verbose_name_plural": "регистрации",
            },
        ),
        migrations.AddField(
            model_name="human",
            name="registration",
            field=models.OneToOneField(
                default=1,
                help_text="Информация о регистрации человека",
                on_delete=django.db.models.deletion.PROTECT,
                to="people.registration",
                verbose_name="регистрация",
            ),
            preserve_default=False,
        ),
    ]
