# Generated by Django 4.2.16 on 2025-04-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0012_registration_human_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invalidity",
            name="group",
            field=models.PositiveIntegerField(
                choices=[(1, "1 группа"), (2, "2 группа"), (3, "3 группа")],
                default=1,
                help_text="группа инвалидности",
                verbose_name="группа",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invalidity",
            name="reason",
            field=models.CharField(
                choices=[
                    ("vov", "Инвалиды, участники ВОВ"),
                    ("combat", "Участники боевых действий"),
                    ("chernobyl", "Чернобыльцы"),
                    ("disease", "По заболеванию"),
                    ("other", "Другое"),
                ],
                default=1,
                help_text="причина инвалидности",
                max_length=64,
                verbose_name="причина",
            ),
            preserve_default=False,
        ),
    ]
