# Generated by Django 4.2.16 on 2025-04-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0013_alter_invalidity_group_alter_invalidity_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invalidity",
            name="disease_details",
        ),
        migrations.RemoveField(
            model_name="invalidity",
            name="other_details",
        ),
        migrations.AddField(
            model_name="invalidity",
            name="details",
            field=models.CharField(
                blank=True,
                help_text="детали инвалидности",
                max_length=255,
                null=True,
                verbose_name="детали",
            ),
        ),
    ]
