# Generated by Django 4.2.16 on 2025-04-03 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0014_remove_invalidity_disease_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="address",
            field=models.CharField(
                help_text="адрес регистрации",
                max_length=255,
                verbose_name="адрес",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="registered_to",
            field=models.DateField(
                blank=True,
                help_text="Дата окончания регистрации",
                null=True,
                verbose_name="зарегистрирован по",
            ),
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("husband", "Муж"),
                            ("wife", "Жена"),
                            ("father", "Отец"),
                            ("mother", "Мать"),
                            ("son", "Сын"),
                            ("daughter", "Дочь"),
                        ],
                        help_text="тип родства",
                        max_length=10,
                        verbose_name="тип",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="дата начала родства",
                        verbose_name="начало родства",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="дата окончания родства",
                        null=True,
                        verbose_name="конец родства",
                    ),
                ),
                (
                    "from_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_people",
                        to="people.human",
                    ),
                ),
                (
                    "to_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_people",
                        to="people.human",
                    ),
                ),
            ],
            options={
                "verbose_name": "родственная связь",
                "verbose_name_plural": "родственные связи",
                "unique_together": {
                    ("from_person", "to_person", "relationship_type")
                },
            },
        ),
        migrations.AddField(
            model_name="human",
            name="relatives",
            field=models.ManyToManyField(
                related_name="related_to",
                through="people.Relationship",
                to="people.human",
            ),
        ),
    ]
