# Generated by Django 4.2.16 on 2025-04-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0016_alter_human_relatives"),
    ]

    operations = [
        migrations.RenameField(
            model_name="human",
            old_name="relatives",
            new_name="relativesss",
        ),
    ]
