# Generated by Django 4.2.16 on 2025-04-03 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0019_alter_human_relatives"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="from_person",
            field=models.ForeignKey(
                help_text="у кокого человека родство",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_people",
                to="people.human",
                verbose_name="у кого родство",
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="to_person",
            field=models.ForeignKey(
                help_text="с кем родство у человека",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_people",
                to="people.human",
                verbose_name="с кем родство",
            ),
        ),
    ]
