# Generated by Django 4.2.16 on 2025-04-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0020_alter_relationship_from_person_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="type_document",
            new_name="document_type",
        ),
    ]
