# Generated by Django 4.2.16 on 2025-04-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0022_alter_invalidity_human"),
    ]

    operations = [
        migrations.AlterField(
            model_name="military",
            name="human",
            field=models.OneToOneField(
                help_text="человек военнообязаности",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="military",
                related_query_name="military",
                to="people.human",
                verbose_name="человек",
            ),
        ),
    ]
