# Generated by Django 4.2.16 on 2025-04-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0023_alter_military_human"),
    ]

    operations = [
        migrations.AddField(
            model_name="military",
            name="called",
            field=models.BooleanField(
                default=False,
                help_text="призван к военной службе",
                verbose_name="призван",
            ),
        ),
    ]
